### PR TITLE
Fix value check logic for ms arg

### PR DESCRIPTION
**Pull request by NeekSandhu**
Failing test as seen in:

https://runkit.com/neeksandhu/5a10bc3c761dce00128e5a33

### CODE REVIEW

**Comment by sindresorhus** [comment]
Can you include the failing test as an actual test here in `test.js`?

**Comment by NeekSandhu** [comment]
Updated.

Anyway for future reference, does GitHub notify when more commits are made to same PR?

**Comment by sindresorhus** [comment]
> Anyway for future reference, does GitHub notify when more commits are made to same PR?

Yes

**Comment by sindresorhus** [comment]
Thanks :)

**Pull request merged**
